declarator_view/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html')),
    path('admin/', admin.site.urls),
    path('declarator/', include('main.urls')),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'declarator'
urlpatterns = [
    path('', views.show_table),
    path('office/<of_id>/', views.offices, name='office')

]

main/models.py
from django.db import models
from mptt.models import TreeForeignKey, MPTTModel
import os
from django.conf import settings


def make_doc_path(instance, filename):
    return os.path.join(settings.MEDIA_ROOT, instance.document.office.name, filename)


# Create your models here.
class Office(MPTTModel):
    parent = TreeForeignKey('self', blank=True, null=True, on_delete=models.PROTECT)
    name = models.TextField(verbose_name='Полное название')
    sort_order = models.IntegerField(default=0, verbose_name='Порядок сортировки')

    def __str__(self):
        return self.name


class Document(models.Model):
    office = models.ForeignKey(Office, verbose_name="Орган власти", on_delete=models.PROTECT)
    income_year = models.IntegerField(verbose_name="Год за который указан доход")

    def __str__(self):
        return '{}, {}'.format(self.office, self.income_year)

    def check_all_files_exist(self):
        files = DocumentFile.objects.filter(document=self.id)
        if files.count() == 0:
            return False
        else:
            return all([bool(f.file) for f in files])

    def check_any_files_exist(self):
        files = DocumentFile.objects.filter(document=self.id)
        return any([bool(f.file) for f in files])


class DocumentFile(models.Model):
    document = models.ForeignKey(Document, verbose_name="Декларация", on_delete=models.PROTECT)
    file = models.FileField(blank=True, max_length=255, null=True, upload_to=make_doc_path, verbose_name="Файл")
    # file равный None означает, что файл должен быть, но отсутствует

    def __str__(self):
        return self.file.__getattribute__('name') if self.file else str(None)

main/views.py
from django.shortcuts import render_to_response, HttpResponse, render
from .models import Office, Document, DocumentFile
from django.template import RequestContext


# Create your views here.
def show_table(request):
    return render_to_response('declarator/table.html', {'nodes': Office.objects.all()}, RequestContext(request))


def offices(request, of_id):
    """
    Cases:
    1. No declaration exists - no mark
    2. There are some declarations, but there aren't any files in any of them - empty mark
    3. There are declarations, but not all of them have files (file is None or doesn't exist) - half-filled mark
    4. There are declarations, all with files - filled mark
    """

    offices = Office.objects.get(pk=of_id).get_children()
    years = tuple(range(2017, 2008, -1))
    data = dict()

    for of in offices:
        data[of] = []
        for year in years:
            docs = Document.objects.filter(office=of.id, income_year=year)

            if docs.count() == 0:
                data[of].append('none')
                continue
            any_files, all_files = False, True
            for doc in docs:
                if doc.check_any_files_exist():
                    any_files = True
                if not doc.check_all_files_exist():
                    all_files = False

            if not any_files:
                data[of].append('blank')
            elif not all_files:
                data[of].append('half')
            elif all_files:
                data[of].append('filled')

    return render(request, 'declarator/office.html', context={'data': data,
                                                              'name': Office.objects.get(pk=of_id).name,
                                                              'years': years,
                                                              })

main/templates/declarator/office.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  {{ name }}
{% endblock %}

{% block content %}
  <table class="table">
    <tr>
      <th>Branch</th>
      {% for year in years %}
        <th>{{ year }}</th>
      {% endfor %}
    </tr>

    {% for of, cases in data.items %}
      <tr>
        <td><a href="{% url 'declarator:office' of.id %}">{{ of.name }}</a></td>
        {% for c in cases %}

          {% if c == 'none' %}
            <td></td>
          {% elif c == 'blank' %}
            <td><img src="{% static 'img/circle_blank.png'%}"></td>
          {% elif c == 'half' %}
            <td><img src="{% static 'img/circle_halffilled.png'%}"></td>
          {% elif c == 'filled' %}
            <td><img src="{% static 'img/circle_filled.png'%}"></td>
          {% endif %}

        {% endfor %}
      </tr>
    {% endfor %}
  </table>
{% endblock %}

main/templates/declarator/table.html
{% extends 'base.html' %}
{% load mptt_tags %}

{% block title %}
  Governmental bodies
{% endblock %}

{% block content %}
  <div class="list-group ">
    {% recursetree nodes %}
      <a href="{% url 'declarator:office' node.id %}" class="list-group-item list-group-item-action">{{ node.name }}</a>
    {% endrecursetree %}
  </div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>

  <link rel="shortcut icon" href="#" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-grid.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-reboot.css' %}">
  <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
  <script src="{% static 'js/bootstrap.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>

</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <ul class="navbar-nav">
      <li class="nav-item"><a class="nav-link" href="/admin/">Admin panel</a></li>
      <li class="nav-item"><a class="nav-link" href="/declarator/">View for Declarator</a></li>
    </ul>
  </nav>

  {% block content %}
  {% endblock %}

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
  Home page
{% endblock %}

{% block content %}
{% endblock %}